server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=${API_AUTH_BASE}/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=${USER_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=${API_USER_BASE}/**, ${API_PAYMENT_CARDS_BASE}/**

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=${ORDER_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=${API_ORDER_BASE}/**, ${API_ITEMS_BASE}/**

jwt.secret=${JWT_SECRET}